import random
from app import create_app, db
from app.models import Category, Subcategory, Product, CartItem, Wishlist, OrderItem

app = create_app()

PRODUCTS_DATA = [
    # Watches
    {'cat': 'Fashion', 'sub': 'Watches', 'brand': 'Rolex', 'name': 'Rolex Submariner Date 41mm', 'price': 1050000, 'img': 'https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=600&auto=format&fit=crop', 'desc': 'The iconic Rolex Submariner Date 41mm in Oystersteel with a Cerachrom bezel. Waterproof to 300 meters, this diving watch features a Chromalight display for excellent visibility in dark conditions.'},
    {'cat': 'Fashion', 'sub': 'Watches', 'brand': 'Omega', 'name': 'Omega Speedmaster Moonwatch Professional', 'price': 485000, 'img': 'https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=600&auto=format&fit=crop', 'desc': 'The legendary Omega Speedmaster Professional, the first watch worn on the moon. Features a Hesalite crystal, manual-winding calibre 3861 movement, and iconic black dial with tachymeter scale.'},
    {'cat': 'Fashion', 'sub': 'Watches', 'brand': 'Tissot', 'name': 'Tissot PRX Powermatic 80', 'price': 75000, 'img': 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=600&auto=format&fit=crop', 'desc': 'Tissot PRX Powermatic 80 with integrated bracelet and 1970s design. Features an automatic movement with 80-hour power reserve, sapphire crystal, and water resistance to 100 meters.'},
    {'cat': 'Fashion', 'sub': 'Watches', 'brand': 'Daniel Wellington', 'name': 'Daniel Wellington Classic Sheffield', 'price': 18500, 'img': 'https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?w=600&auto=format&fit=crop', 'desc': 'Elegant Daniel Wellington Classic Sheffield with mesh bracelet. Features a minimalist white dial, slim profile, and Japanese quartz movement. Perfect for both formal and casual occasions.'},
    {'cat': 'Fashion', 'sub': 'Watches', 'brand': 'Cartier', 'name': 'Cartier Tank Must Watch', 'price': 285000, 'img': 'https://images.unsplash.com/photo-1539874754764-5a96559165b0?w=600&auto=format&fit=crop', 'desc': 'The legendary Cartier Tank Must with Roman numerals and blue steel hands. Features quartz movement, sapphire crystal, and the iconic rectangular case that has defined elegance since 1917.'},
    {'cat': 'Fashion', 'sub': 'Watches', 'brand': 'Patek Philippe', 'name': 'Patek Philippe Calatrava', 'price': 1850000, 'img': 'https://images.unsplash.com/photo-1547996160-81dfa63595aa?w=600&auto=format&fit=crop', 'desc': 'Patek Philippe Calatrava in white gold with manual movement. Features classic round case, hobnail bezel, and the brand\'s signature understated elegance. A true investment piece.'},
    {'cat': 'Fashion', 'sub': 'Watches', 'brand': 'Audemars Piguet', 'name': 'Audemars Piguet Royal Oak', 'price': 2250000, 'img': 'https://images.unsplash.com/photo-1547996160-81dfa63595aa?w=600&auto=format&fit=crop', 'desc': 'Audemars Piguet Royal Oak in stainless steel with integrated bracelet. Features the iconic octagonal bezel, tapisserie dial, and self-winding movement. The definitive luxury sports watch.'},
    {'cat': 'Fashion', 'sub': 'Watches', 'brand': 'Breitling', 'name': 'Breitling Navitimer B01', 'price': 525000, 'img': 'https://images.unsplash.com/photo-1585123334904-845d60e97b29?w=600&auto=format&fit=crop', 'desc': 'Breitling Navitimer B01 with chronograph and slide rule bezel. Features in-house movement, 43mm case, and the iconic pilot watch design. A legend in aviation timepieces.'},
    
    # Bags
    {'cat': 'Fashion', 'sub': 'Bags', 'brand': 'Louis Vuitton', 'name': 'Louis Vuitton Neverfull MM Monogram', 'price': 165000, 'img': 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600&auto=format&fit=crop', 'desc': 'The iconic Louis Vuitton Neverfull MM in classic Monogram canvas. Features spacious interior, removable pouch, and signature natural cowhide leather trim. A timeless everyday luxury tote.'},
    {'cat': 'Fashion', 'sub': 'Bags', 'brand': 'Prada', 'name': 'Prada Re-Nylon Backpack', 'price': 145000, 'img': 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&auto=format&fit=crop', 'desc': 'Sustainable Prada Re-Nylon backpack made from regenerated nylon. Features triangle logo, multiple compartments, and adjustable shoulder straps. Modern luxury meets environmental consciousness.'},
    {'cat': 'Fashion', 'sub': 'Bags', 'brand': 'Chanel', 'name': 'Chanel Classic Flap Bag Medium', 'price': 485000, 'img': 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop', 'desc': 'The legendary Chanel Classic Flap Bag in medium size with quilted lambskin and gold-tone hardware. Features the iconic interlocking CC turn-lock, chain strap, and elegant burgundy interior lining.'},
    {'cat': 'Fashion', 'sub': 'Bags', 'brand': 'Hermes', 'name': 'Hermes Birkin 35 Togo Gold', 'price': 850000, 'img': 'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=600&auto=format&fit=crop', 'desc': 'The holy grail of luxury handbags, Hermes Birkin 35 in Togo gold leather. Features palladium hardware, rolled handles, and the iconic saddle stitch. The ultimate investment piece.'},
    {'cat': 'Fashion', 'sub': 'Bags', 'brand': 'Gucci', 'name': 'Gucci Dionysus GG Supreme Bag', 'price': 185000, 'img': 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=600&auto=format&fit=crop', 'desc': 'Gucci Dionysus bag in GG Supreme canvas with tiger head closure. Features chain shoulder strap, suede interior, and Alessandro Michele\'s signature design. Modern luxury redefined.'},
    {'cat': 'Fashion', 'sub': 'Bags', 'brand': 'Dior', 'name': 'Dior Lady Dior Medium Bag', 'price': 385000, 'img': 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600&auto=format&fit=crop', 'desc': 'Dior Lady Dior bag in cannage lambskin with gold hardware. Features top handles, removable shoulder strap, and the iconic quilted pattern. Named after Princess Diana.'},
    {'cat': 'Fashion', 'sub': 'Bags', 'brand': 'Fendi', 'name': 'Fendi Baguette Medium Leather', 'price': 245000, 'img': 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=600&auto=format&fit=crop', 'desc': 'Fendi Baguette in medium size with FF logo hardware. Features structured silhouette, flap closure, and the bag that defined 90s luxury fashion. A timeless classic.'},
    {'cat': 'Fashion', 'sub': 'Bags', 'brand': 'Celine', 'name': 'Celine Triomphe Canvas Belt Bag', 'price': 195000, 'img': 'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=600&auto=format&fit=crop', 'desc': 'Celine Triomphe belt bag in canvas with leather trim. Features adjustable belt, front zip pocket, and the iconic Triomphe buckle. Perfect for modern luxury on the go.'},
    
    # Clothing
    {'cat': 'Fashion', 'sub': 'Clothing', 'brand': 'Balenciaga', 'name': 'Balenciaga Oversized Hoodie Black', 'price': 65000, 'img': 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=600&auto=format&fit=crop', 'desc': 'Balenciaga oversized hoodie in premium cotton with dropped shoulders and signature logo. Features a relaxed fit, ribbed trim, and the brand\'s iconic streetwear aesthetic.'},
    {'cat': 'Fashion', 'sub': 'Clothing', 'brand': 'Tom Ford', 'name': 'Tom Ford Slim Fit Wool Suit', 'price': 285000, 'img': 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&auto=format&fit=crop', 'desc': 'Impeccably tailored Tom Ford slim fit suit in Italian wool. Features notch lapels, two-button closure, and the brand\'s signature sophisticated silhouette. The epitome of modern elegance.'},
    {'cat': 'Fashion', 'sub': 'Clothing', 'brand': 'Gucci', 'name': 'Gucci GG Silk Dress', 'price': 185000, 'img': 'https://images.unsplash.com/photo-1539008835657-9e8e9680c956?w=600&auto=format&fit=crop', 'desc': 'Gucci silk midi dress with iconic GG monogram print. Features a flattering V-neckline, flowing silhouette, and the brand\'s signature vintage-inspired design. Perfect for elegant occasions.'},
    {'cat': 'Fashion', 'sub': 'Clothing', 'brand': 'Versace', 'name': 'Versace Medusa Silk Shirt', 'price': 85000, 'img': 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&auto=format&fit=crop', 'desc': 'Versace silk shirt with Medusa head print. Features pointed collar, mother-of-pearl buttons, and the brand\'s bold aesthetic. Italian luxury at its most expressive.'},
    {'cat': 'Fashion', 'sub': 'Clothing', 'brand': 'Burberry', 'name': 'Burberry Heritage Trench Coat', 'price': 145000, 'img': 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&auto=format&fit=crop', 'desc': 'Burberry Heritage trench coat in gabardine cotton. Features double-breasted design, storm shield, and the iconic check lining. A timeless British classic since 1856.'},
    {'cat': 'Fashion', 'sub': 'Clothing', 'brand': 'Ralph Lauren', 'name': 'Ralph Lauren Purple Label Cashmere Sweater', 'price': 75000, 'img': 'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=600&auto=format&fit=crop', 'desc': 'Ralph Lauren Purple Label cashmere crewneck sweater. Features ribbed trim, premium Italian cashmere, and understated elegance. The pinnacle of American luxury knitwear.'},
    {'cat': 'Fashion', 'sub': 'Clothing', 'brand': 'Saint Laurent', 'name': 'Saint Laurent Le Smoking Tuxedo', 'price': 325000, 'img': 'https://images.unsplash.com/photo-1593030761757-71fae45fa0e7?w=600&auto=format&fit=crop', 'desc': 'Saint Laurent Le Smoking tuxedo in black wool crepe. Features satin lapels, slim trousers, and the iconic androgynous design that revolutionized womenswear. YSL at its finest.'},
    {'cat': 'Fashion', 'sub': 'Clothing', 'brand': 'Brunello Cucinelli', 'name': 'Brunello Cucinelli Cashmere Cardigan', 'price': 125000, 'img': 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=600&auto=format&fit=crop', 'desc': 'Brunello Cucinelli cashmere cardigan with monile details. Features hand-finished edges, mother-of-pearl buttons, and Italian craftsmanship. Ethical luxury from Solomeo.'},
    
    # Shoes
    {'cat': 'Fashion', 'sub': 'Shoes', 'brand': 'Christian Louboutin', 'name': 'Louboutin So Kate Patent Leather Pumps', 'price': 85000, 'img': 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600&auto=format&fit=crop', 'desc': 'Christian Louboutin So Kate pumps in red patent leather with the iconic 120mm heel. Features the signature red sole, pointed toe, and leg-lengthening silhouette. The ultimate statement pump.'},
    {'cat': 'Fashion', 'sub': 'Shoes', 'brand': 'Gucci', 'name': 'Gucci Ace Sneakers White Leather', 'price': 65000, 'img': 'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=600&auto=format&fit=crop', 'desc': 'Gucci Ace low-top sneakers in white leather with green and red Web trim. Features signature GG motif, rubber sole, and the brand\'s iconic tennis shoe design. Luxury casual at its finest.'},
    {'cat': 'Fashion', 'sub': 'Shoes', 'brand': 'Balenciaga', 'name': 'Balenciaga Triple S Sneakers', 'price': 95000, 'img': 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop', 'desc': 'Balenciaga Triple S sneakers in multi-panel leather with oversized chunky sole. Features the brand\'s signature distressed aesthetic, complex layering, and bold streetwear presence.'},
    {'cat': 'Fashion', 'sub': 'Shoes', 'brand': 'Berluti', 'name': 'Berluti Patina Leather Oxford Shoes', 'price': 125000, 'img': 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600&auto=format&fit=crop', 'desc': 'Handcrafted Berluti Oxford shoes in Venezia leather with signature patina. Features Goodyear construction, classic cap-toe design, and the brand\'s legendary artisanal craftsmanship.'},
    {'cat': 'Fashion', 'sub': 'Shoes', 'brand': 'Jimmy Choo', 'name': 'Jimmy Choo Romy 85 Pumps', 'price': 75000, 'img': 'https://images.unsplash.com/photo-1560343090-f0409e92791a?w=600&auto=format&fit=crop', 'desc': 'Jimmy Choo Romy pumps in glitter with 85mm heel. Features pointed toe, leather sole, and crystal embellishment. The perfect shoe for red carpet moments.'},
    {'cat': 'Fashion', 'sub': 'Shoes', 'brand': 'Manolo Blahnik', 'name': 'Manolo Blahnik Hangisi Satin Pumps', 'price': 95000, 'img': 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600&auto=format&fit=crop', 'desc': 'Manolo Blahnik Hangisi pumps in blue satin with crystal buckle. Features 105mm heel, leather sole, and the iconic Sex and the City design. Couture footwear at its finest.'},
    {'cat': 'Fashion', 'sub': 'Shoes', 'brand': 'Alexander McQueen', 'name': 'Alexander McQueen Oversized Sneakers', 'price': 85000, 'img': 'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=600&auto=format&fit=crop', 'desc': 'Alexander McQueen oversized sneakers in leather with oversized sole. Features contrast stitching, heel counter, and the brand\'s avant-garde design. Statement footwear for the bold.'},
    {'cat': 'Fashion', 'sub': 'Shoes', 'brand': 'Salvatore Ferragamo', 'name': 'Salvatore Ferragamo Varina Flats', 'price': 55000, 'img': 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600&auto=format&fit=crop', 'desc': 'Salvatore Ferragamo Varina ballet flats in patent leather. Features Vara bow detail, leather sole, and Italian craftsmanship. Elegant comfort for everyday luxury.'},
    
    # Smartphones
    {'cat': 'Premium Tech', 'sub': 'Smartphones', 'brand': 'Apple', 'name': 'iPhone 15 Pro Max 256GB Titanium', 'price': 159900, 'img': 'https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=600&auto=format&fit=crop', 'desc': 'Apple iPhone 15 Pro Max in Titanium with A17 Pro chip. Features 48MP camera system, Dynamic Island, and the most powerful iPhone ever. Premium design meets cutting-edge technology.'},
    {'cat': 'Premium Tech', 'sub': 'Smartphones', 'brand': 'Samsung', 'name': 'Samsung Galaxy S24 Ultra 512GB', 'price': 134999, 'img': 'https://images.unsplash.com/photo-1556656793-08538906a9f8?w=600&auto=format&fit=crop', 'desc': 'Samsung Galaxy S24 Ultra with S Pen and AI features. Features 200MP camera, 6.8" Dynamic AMOLED display, and titanium frame. The ultimate Android flagship experience.'},
    {'cat': 'Premium Tech', 'sub': 'Smartphones', 'brand': 'Google', 'name': 'Google Pixel 8 Pro 256GB', 'price': 106999, 'img': 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&auto=format&fit=crop', 'desc': 'Google Pixel 8 Pro with advanced AI photography. Features Tensor G3 chip, 50MP telephoto lens, and 7 years of software updates. Pure Android experience with intelligent features.'},
    {'cat': 'Premium Tech', 'sub': 'Smartphones', 'brand': 'OnePlus', 'name': 'OnePlus 12 512GB', 'price': 64999, 'img': 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=600&auto=format&fit=crop', 'desc': 'OnePlus 12 with Snapdragon 8 Gen 3 and Hasselblad camera. Features 6.82" LTPO AMOLED display, 100W charging, and the fastest performance in its class. Flagship killer redefined.'},
    {'cat': 'Premium Tech', 'sub': 'Smartphones', 'brand': 'Xiaomi', 'name': 'Xiaomi 14 Ultra 512GB', 'price': 99999, 'img': 'https://images.unsplash.com/photo-1556656793-08538906a9f8?w=600&auto=format&fit=crop', 'desc': 'Xiaomi 14 Ultra with Leica optics and Snapdragon 8 Gen 3. Features 1" sensor, 120W HyperCharge, and professional-grade photography. The camera phone for enthusiasts.'},
    {'cat': 'Premium Tech', 'sub': 'Smartphones', 'brand': 'Nothing', 'name': 'Nothing Phone 2 256GB', 'price': 44999, 'img': 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=600&auto=format&fit=crop', 'desc': 'Nothing Phone 2 with Glyph Interface and transparent design. Features Snapdragon 8+ Gen 1, unique notification lights, and a design philosophy that breaks conventions. The future of smartphones.'},
    
    # Laptops
    {'cat': 'Premium Tech', 'sub': 'Laptops', 'brand': 'Apple', 'name': 'MacBook Pro 16" M3 Max 512GB', 'price': 349900, 'img': 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&auto=format&fit=crop', 'desc': 'Apple MacBook Pro 16" with M3 Max chip. Features Liquid Retina XDR display, up to 22 hours battery life, and professional performance for creative workflows. The ultimate pro laptop.'},
    {'cat': 'Premium Tech', 'sub': 'Laptops', 'brand': 'Apple', 'name': 'MacBook Air 15" M3 256GB', 'price': 134900, 'img': 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&auto=format&fit=crop', 'desc': 'Apple MacBook Air 15" with M3 chip. Features stunning Liquid Retina display, 18-hour battery life, and fanless silent design. Perfect thin-and-light laptop for everyday luxury.'},
    {'cat': 'Premium Tech', 'sub': 'Laptops', 'brand': 'Microsoft', 'name': 'Surface Laptop Studio 2 i7 32GB', 'price': 269999, 'img': 'https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=600&auto=format&fit=crop', 'desc': 'Microsoft Surface Laptop Studio 2 with unique 3-in-1 design. Features Intel Core i7, NVIDIA RTX GPU, and dynamic woven hinge. The most versatile Surface ever created.'},
    {'cat': 'Premium Tech', 'sub': 'Laptops', 'brand': 'Dell', 'name': 'Dell XPS 15 OLED i9 32GB', 'price': 285000, 'img': 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=600&auto=format&fit=crop', 'desc': 'Dell XPS 15 with stunning OLED display and Intel Core i9. Features NVIDIA RTX graphics, premium build quality, and Windows Hello. The Windows equivalent of MacBook Pro.'},
    {'cat': 'Premium Tech', 'sub': 'Laptops', 'brand': 'Razer', 'name': 'Razer Blade 16 OLED i9 32GB', 'price': 325000, 'img': 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=600&auto=format&fit=crop', 'desc': 'Razer Blade 16 with OLED display and RTX 4090. Features CNC aluminum chassis, per-key RGB, and the most powerful gaming laptop in a portable form factor. Gaming luxury.'},
    {'cat': 'Premium Tech', 'sub': 'Laptops', 'brand': 'Lenovo', 'name': 'Lenovo ThinkPad X1 Carbon i7 16GB', 'price': 195000, 'img': 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=600&auto=format&fit=crop', 'desc': 'Lenovo ThinkPad X1 Carbon with carbon fiber construction. Features Intel Core i7, OLED display, and legendary ThinkPad durability. The ultimate business laptop.'},
    
    # Audio
    {'cat': 'Premium Tech', 'sub': 'Audio', 'brand': 'Bose', 'name': 'Bose QuietComfort Ultra Headphones', 'price': 34990, 'img': 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop', 'desc': 'Bose QuietComfort Ultra with world-class noise cancellation. Features CustomTune technology, spatial audio, and up to 24 hours battery life. The gold standard in premium audio.'},
    {'cat': 'Premium Tech', 'sub': 'Audio', 'brand': 'Sony', 'name': 'Sony WH-1000XM5 Wireless Headphones', 'price': 29990, 'img': 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=600&auto=format&fit=crop', 'desc': 'Sony WH-1000XM5 with industry-leading noise cancellation. Features 8 microphones, 30-hour battery, and lightweight design. Premium sound meets exceptional comfort.'},
    {'cat': 'Premium Tech', 'sub': 'Audio', 'brand': 'Sennheiser', 'name': 'Sennheiser Momentum 4 Wireless', 'price': 34990, 'img': 'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=600&auto=format&fit=crop', 'desc': 'Sennheiser Momentum 4 with signature sound. Features 60-hour battery, aptX Adaptive, and premium materials. Audiophile-grade sound in a sophisticated wireless package.'},
    {'cat': 'Premium Tech', 'sub': 'Audio', 'brand': 'Apple', 'name': 'AirPods Max Silver', 'price': 59900, 'img': 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=600&auto=format&fit=crop', 'desc': 'Apple AirPods Max in silver with Active Noise Cancellation. Features computational audio, transparency mode, and seamless Apple ecosystem integration. Premium over-ear headphones.'},
    {'cat': 'Premium Tech', 'sub': 'Audio', 'brand': 'Bang & Olufsen', 'name': 'B&O Beoplay HX Headphones', 'price': 44990, 'img': 'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=600&auto=format&fit=crop', 'desc': 'Bang & Olufsen Beoplay HX with adaptive ANC. Features premium materials, 30-hour battery, and Danish design excellence. Luxury audio with Scandinavian aesthetics.'},
    {'cat': 'Premium Tech', 'sub': 'Audio', 'brand': 'Marshall', 'name': 'Marshall Major IV Headphones', 'price': 14990, 'img': 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop', 'desc': 'Marshall Major IV with iconic design and 80+ hour battery. Features wireless charging, custom-tuned drivers, and the classic rock aesthetic. Legendary sound heritage.'},
    
    # Smartwatches
    {'cat': 'Premium Tech', 'sub': 'Smartwatches', 'brand': 'Apple', 'name': 'Apple Watch Series 9 GPS 45mm', 'price': 44900, 'img': 'https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?w=600&auto=format&fit=crop', 'desc': 'Apple Watch Series 9 with S9 chip and Double Tap gesture. Features always-on Retina display, advanced health sensors, and seamless iPhone integration. The most advanced smartwatch.'},
    {'cat': 'Premium Tech', 'sub': 'Smartwatches', 'brand': 'Garmin', 'name': 'Garmin Fenix 7 Pro Solar', 'price': 79990, 'img': 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=600&auto=format&fit=crop', 'desc': 'Garmin Fenix 7 Pro Solar with solar charging. Features multi-sport GPS, advanced health monitoring, and infinite battery life in smartwatch mode. The ultimate adventure watch.'},
    {'cat': 'Premium Tech', 'sub': 'Smartwatches', 'brand': 'Tag Heuer', 'name': 'Tag Heuer Connected Calibre E4 45mm', 'price': 185000, 'img': 'https://images.unsplash.com/photo-1546868871-af0de0ae72be?w=600&auto=format&fit=crop', 'desc': 'Tag Heuer Connected Calibre E4 with OLED touchscreen. Features Swiss-made craftsmanship, golf tracking, and luxury sports watch design. Where tradition meets innovation.'},
    {'cat': 'Premium Tech', 'sub': 'Smartwatches', 'brand': 'Samsung', 'name': 'Samsung Galaxy Watch 6 Classic', 'price': 32990, 'img': 'https://images.unsplash.com/photo-1546868871-af0de0ae72be?w=600&auto=format&fit=crop', 'desc': 'Samsung Galaxy Watch 6 Classic with rotating bezel. Features BioActive sensor, sleep tracking, and classic watch design. The perfect blend of tradition and technology.'},
    {'cat': 'Premium Tech', 'sub': 'Smartwatches', 'brand': 'Withings', 'name': 'Withings ScanWatch Horizon', 'price': 37990, 'img': 'https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?w=600&auto=format&fit=crop', 'desc': 'Withings ScanWatch Horizon with sapphire crystal and rotating bezel. Features 30-day battery, ECG, and medical-grade health monitoring. Luxury hybrid smartwatch.'},
    {'cat': 'Premium Tech', 'sub': 'Smartwatches', 'brand': 'Montblanc', 'name': 'Montblanc Summit 3', 'price': 125000, 'img': 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=600&auto=format&fit=crop', 'desc': 'Montblanc Summit 3 with digital crown and sapphire crystal. Features Wear OS, premium leather strap, and Swiss watch heritage. Traditional luxury meets smart technology.'},
    
    # Home Decor
    {'cat': 'Lifestyle', 'sub': 'Home Decor', 'brand': 'Baccarat', 'name': 'Baccarat Harmonie Crystal Vase', 'price': 85000, 'img': 'https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?w=600&auto=format&fit=crop', 'desc': 'Baccarat Harmonie vase in hand-cut crystal. Features diamond-cut pattern, timeless silhouette, and 250 years of French crystal craftsmanship. A stunning centerpiece for any luxury home.'},
    {'cat': 'Lifestyle', 'sub': 'Home Decor', 'brand': 'Flos', 'name': 'Flos IC Lights T1 Table Lamp', 'price': 65000, 'img': 'https://images.unsplash.com/photo-1506898667547-42e22a46e125?w=600&auto=format&fit=crop', 'desc': 'Flos IC Lights T1 table lamp by Michael Anastassiades. Features blown glass opal diffuser, brass body, and elegant dimmer switch. Modern Italian design at its finest.'},
    {'cat': 'Lifestyle', 'sub': 'Home Decor', 'brand': 'Hermes', 'name': 'Hermes Avalon Blanket Throw', 'price': 125000, 'img': 'https://images.unsplash.com/photo-1544457070-4cd773b4d71e?w=600&auto=format&fit=crop', 'desc': 'Hermes Avalon blanket in 100% cashmere with signature H motif. Features ultra-soft texture, elegant fringe trim, and the brand\'s legendary equestrian heritage. Pure luxury comfort.'},
    {'cat': 'Lifestyle', 'sub': 'Home Decor', 'brand': 'Vitra', 'name': 'Vitra Eames Lounge Chair', 'price': 485000, 'img': 'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=600&auto=format&fit=crop', 'desc': 'Vitra Eames Lounge Chair with ottoman in molded plywood and leather. Features iconic mid-century design, premium materials, and the most comfortable chair ever made. Design legend.'},
    {'cat': 'Lifestyle', 'sub': 'Home Decor', 'brand': 'Artemide', 'name': 'Artemide Tolomeo Floor Lamp', 'price': 55000, 'img': 'https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?w=600&auto=format&fit=crop', 'desc': 'Artemide Tolomeo floor lamp by Michele De Lucchi. Features articulated arms, adjustable diffuser, and Italian engineering excellence. The perfect task lamp for modern spaces.'},
    {'cat': 'Lifestyle', 'sub': 'Home Decor', 'brand': 'Kartell', 'name': 'Kartell Componibili Storage', 'price': 35000, 'img': 'https://images.unsplash.com/photo-1544457070-4cd773b4d71e?w=600&auto=format&fit=crop', 'desc': 'Kartell Componibili modular storage units in plastic. Features stackable design, sliding doors, and Anna Castelli Ferrieri\'s iconic 1969 design. Functional Italian design.'},
    
    # Fragrances
    {'cat': 'Lifestyle', 'sub': 'Fragrances', 'brand': 'Chanel', 'name': 'Chanel Bleu de Chanel EDP 100ml', 'price': 14500, 'img': 'https://images.unsplash.com/photo-1541643600914-78b084683601?w=600&auto=format&fit=crop', 'desc': 'Chanel Bleu de Chanel Eau de Parfum for men. Features woody aromatic notes with citrus and cedar. A sophisticated and magnetic fragrance that embodies freedom and elegance.'},
    {'cat': 'Lifestyle', 'sub': 'Fragrances', 'brand': 'Tom Ford', 'name': 'Tom Ford Oud Wood EDP 100ml', 'price': 28500, 'img': 'https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?w=600&auto=format&fit=crop', 'desc': 'Tom Ford Oud Wood Eau de Parfum. Features rare oud wood, sandalwood, and rosewood. One of the most original and recognizable fragrances in the world. Rich, warm, and sophisticated.'},
    {'cat': 'Lifestyle', 'sub': 'Fragrances', 'brand': 'Creed', 'name': 'Creed Aventus EDP 100ml', 'price': 38500, 'img': 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=600&auto=format&fit=crop', 'desc': 'Creed Aventus Eau de Parfum inspired by dramatic life. Features pineapple, birch, and musk notes. A sophisticated and bold fragrance for the confident modern man. The best-selling Creed scent.'},
    {'cat': 'Lifestyle', 'sub': 'Fragrances', 'brand': 'Dior', 'name': 'Dior Sauvage EDP 100ml', 'price': 12500, 'img': 'https://images.unsplash.com/photo-1595425930338-5b7ac6e731f2?w=600&auto=format&fit=crop', 'desc': 'Dior Sauvage Eau de Parfum with raw and noble notes. Features bergamot, ambroxan, and pepper. A powerful and fresh fragrance that embodies the spirit of the wild.'},
    {'cat': 'Lifestyle', 'sub': 'Fragrances', 'brand': 'Jo Malone', 'name': 'Jo Malone Wood Sage & Sea Salt', 'price': 16500, 'img': 'https://images.unsplash.com/photo-1541643600914-78b084683601?w=600&auto=format&fit=crop', 'desc': 'Jo Malone Wood Sage & Sea Salt cologne. Features ambrette seeds, sea salt, and sage. A minimalist and sophisticated fragrance that captures the essence of the British coast.'},
    {'cat': 'Lifestyle', 'sub': 'Fragrances', 'brand': 'Maison Francis Kurkdjian', 'name': 'MFK Baccarat Rouge 540 EDP', 'price': 45000, 'img': 'https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?w=600&auto=format&fit=crop', 'desc': 'Maison Francis Kurkdjian Baccarat Rouge 540. Features saffron, jasmine, and ambergris. An intoxicating and radiant fragrance that has become a modern icon. The scent of luxury.'},
    
    # Accessories
    {'cat': 'Lifestyle', 'sub': 'Accessories', 'brand': 'Ray-Ban', 'name': 'Ray-Ban Aviator Classic Gold', 'price': 18500, 'img': 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=600&auto=format&fit=crop', 'desc': 'Ray-Ban Aviator Classic with gold frame and gradient lenses. Features teardrop shape, G-15 crystal lenses, and the iconic design that has defined cool for generations. Timeless American style.'},
    {'cat': 'Lifestyle', 'sub': 'Accessories', 'brand': 'Cartier', 'name': 'Cartier Love Ring 18K Gold', 'price': 285000, 'img': 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600&auto=format&fit=crop', 'desc': 'Cartier Love ring in 18K yellow gold. Features iconic screw motif, oval design, and the symbol of passionate attachment. A timeless piece of jewelry that represents eternal love.'},
    {'cat': 'Lifestyle', 'sub': 'Accessories', 'brand': 'Montblanc', 'name': 'Montblanc Meisterstuck Classique Fountain Pen', 'price': 45000, 'img': 'https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?w=600&auto=format&fit=crop', 'desc': 'Montblanc Meisterstuck Classique fountain pen in black precious resin with gold trim. Features handcrafted 14K gold nib and piston filling mechanism. The pinnacle of writing instruments since 1924.'},
    {'cat': 'Lifestyle', 'sub': 'Accessories', 'brand': 'Tiffany & Co.', 'name': 'Tiffany T Wire Bracelet', 'price': 145000, 'img': 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600&auto=format&fit=crop', 'desc': 'Tiffany T Wire bracelet in 18K rose gold. Features minimalist T motif, diamond accents, and the iconic blue box. Modern luxury from the legendary American jeweler.'},
    {'cat': 'Lifestyle', 'sub': 'Accessories', 'brand': 'Hermes', 'name': 'Hermes Collier de Chien Belt', 'price': 85000, 'img': 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600&auto=format&fit=crop', 'desc': 'Hermes Collier de Chien belt in Swift calfskin with palladium hardware. Features iconic dog collar design, medallion buckle, and French craftsmanship. The ultimate luxury belt.'},
    {'cat': 'Lifestyle', 'sub': 'Accessories', 'brand': 'Bvlgari', 'name': 'Bvlgari Serpenti Ring', 'price': 385000, 'img': 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600&auto=format&fit=crop', 'desc': 'Bvlgari Serpenti ring in 18K white gold with emerald eyes. Features coiled snake design, diamond scales, and Roman jewelry heritage. A statement piece from the iconic Italian jeweler.'},
    {'cat': 'Lifestyle', 'sub': 'Accessories', 'brand': 'Oakley', 'name': 'Oakley Holbrook XL Polarized', 'price': 18500, 'img': 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&auto=format&fit=crop', 'desc': 'Oakley Holbrook XL with polarized lenses. Features O-Matter frame, High Definition Optics, and classic American design. Performance eyewear that looks as good as it performs.'},
    {'cat': 'Lifestyle', 'sub': 'Accessories', 'brand': 'Gucci', 'name': 'Gucci GG Marmont Belt', 'price': 45000, 'img': 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600&auto=format&fit=crop', 'desc': 'Gucci GG Marmont belt in leather with double G buckle. Features black leather, gold-tone hardware, and the iconic interlocking GG logo. Italian luxury for everyday wear.'},
    
    # Art
    {'cat': 'Lifestyle', 'sub': 'Art', 'brand': 'Tate', 'name': 'Abstract Expressionist Canvas Print', 'price': 75000, 'img': 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600&auto=format&fit=crop', 'desc': 'Museum-quality abstract expressionist canvas print. Features bold brushstrokes, vibrant colors, and gallery-wrapped edges. A stunning statement piece that brings contemporary art to your space.'},
    {'cat': 'Lifestyle', 'sub': 'Art', 'brand': 'Saatchi Art', 'name': 'Contemporary Minimalist Photography Print', 'price': 55000, 'img': 'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=600&auto=format&fit=crop', 'desc': 'Limited edition minimalist photography print. Features clean lines, subtle tones, and museum-grade archival paper. Sophisticated wall art for the modern aesthetic home.'},
    {'cat': 'Lifestyle', 'sub': 'Art', 'brand': '1stDibs', 'name': 'Vintage Mid-Century Modern Sculpture', 'price': 165000, 'img': 'https://images.unsplash.com/photo-1561214115-f2f134cc4912?w=600&auto=format&fit=crop', 'desc': 'Authentic vintage mid-century modern sculpture. Features organic forms, brass construction, and provenance documentation. A rare collectible piece for the discerning art collector.'},
    {'cat': 'Lifestyle', 'sub': 'Art', 'brand': 'Christies', 'name': 'Contemporary Oil Painting on Canvas', 'price': 285000, 'img': 'https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=600&auto=format&fit=crop', 'desc': 'Original contemporary oil painting on stretched canvas. Features layered textures, rich pigments, and artist signature. Investment-grade artwork for serious collectors.'},
    {'cat': 'Lifestyle', 'sub': 'Art', 'brand': 'Sothebys', 'name': 'Limited Edition Serigraph Print', 'price': 95000, 'img': 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600&auto=format&fit=crop', 'desc': 'Limited edition serigraph print numbered and signed by the artist. Features museum-quality paper, archival inks, and certificate of authenticity. Collectible fine art.'},
    {'cat': 'Lifestyle', 'sub': 'Art', 'brand': 'Phillips', 'name': 'Modern Bronze Sculpture', 'price': 385000, 'img': 'https://images.unsplash.com/photo-1561214115-f2f134cc4912?w=600&auto=format&fit=crop', 'desc': 'Hand-cast modern bronze sculpture with patina finish. Features abstract forms, solid bronze construction, and artist foundry mark. Three-dimensional art for luxury interiors.'},
    
    # Jewelry (New Category)
    {'cat': 'Lifestyle', 'sub': 'Jewelry', 'brand': 'Tiffany & Co.', 'name': 'Tiffany T True Wire Ring', 'price': 185000, 'img': 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600&auto=format&fit=crop', 'desc': 'Tiffany T True Wire ring in 18K rose gold with diamonds. Features minimalist T motif, brilliant-cut diamonds, and the iconic Tiffany craftsmanship. Modern luxury jewelry.'},
    {'cat': 'Lifestyle', 'sub': 'Jewelry', 'brand': 'Van Cleef & Arpels', 'name': 'Van Cleef Alhambra Necklace', 'price': 485000, 'img': 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600&auto=format&fit=crop', 'desc': 'Van Cleef & Arpels Alhambra necklace in 18K yellow gold with mother-of-pearl. Features iconic clover design, beaded edge, and French jewelry heritage. The symbol of luck.'},
    {'cat': 'Lifestyle', 'sub': 'Jewelry', 'brand': 'Harry Winston', 'name': 'Harry Winston Diamond Stud Earrings', 'price': 1250000, 'img': 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600&auto=format&fit=crop', 'desc': 'Harry Winston diamond stud earrings in platinum. Features brilliant-cut diamonds, exceptional clarity, and the "King of Diamonds" legacy. Ultimate luxury earrings.'},
    {'cat': 'Lifestyle', 'sub': 'Jewelry', 'brand': 'Bulgari', 'name': 'Bulgari Serpenti Necklace', 'price': 850000, 'img': 'https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?w=600&auto=format&fit=crop', 'desc': 'Bulgari Serpenti necklace in 18K white gold with emeralds. Features coiled snake design, pavé diamonds, and Roman jewelry tradition. Iconic Italian luxury.'},
    {'cat': 'Lifestyle', 'sub': 'Jewelry', 'brand': 'Chopard', 'name': 'Chopard Happy Diamonds Pendant', 'price': 385000, 'img': 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600&auto=format&fit=crop', 'desc': 'Chopard Happy Diamonds pendant in 18K white gold. Features floating diamonds between sapphire crystals, playful design, and Swiss jewelry excellence. Joyful luxury.'},
    {'cat': 'Lifestyle', 'sub': 'Jewelry', 'brand': 'Piaget', 'name': 'Piaget Possession Ring', 'price': 285000, 'img': 'https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?w=600&auto=format&fit=crop', 'desc': 'Piaget Possession ring in 18K rose gold with diamonds. Features rotating band, brilliant-cut diamonds, and the brand\'s signature playful elegance. Swiss luxury jewelry.'},
    
    # Eyewear (New Category)
    {'cat': 'Lifestyle', 'sub': 'Eyewear', 'brand': 'Tom Ford', 'name': 'Tom Ford FT5402 Eyeglasses', 'price': 35000, 'img': 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&auto=format&fit=crop', 'desc': 'Tom Ford FT5402 eyeglasses in acetate with T temple. Features bold square frame, premium Italian acetate, and the iconic T logo. Sophisticated eyewear for the modern professional.'},
    {'cat': 'Lifestyle', 'sub': 'Eyewear', 'brand': 'Oliver Peoples', 'name': 'Oliver Peoples Gregory Peck', 'price': 28500, 'img': 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=600&auto=format&fit=crop', 'desc': 'Oliver Peoples Gregory Peck in acetate with filigree detail. Features vintage-inspired design, hand-polished frames, and Hollywood heritage. Classic American eyewear.'},
    {'cat': 'Lifestyle', 'sub': 'Eyewear', 'brand': 'Cartier', 'name': 'Cartier Santos Sunglasses', 'price': 65000, 'img': 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&auto=format&fit=crop', 'desc': 'Cartier Santos de Cartier sunglasses in gold with lenses. Features square aviator shape, C decor, and French luxury heritage. Iconic design since 1904.'},
    {'cat': 'Lifestyle', 'sub': 'Eyewear', 'brand': 'Gucci', 'name': 'Gucci GG0365S Sunglasses', 'price': 45000, 'img': 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=600&auto=format&fit=crop', 'desc': 'Gucci GG0365S sunglasses in acetate with Web detail. Features oversized square frame, GG logo, and Italian craftsmanship. Bold luxury eyewear.'},
    {'cat': 'Lifestyle', 'sub': 'Eyewear', 'brand': 'Prada', 'name': 'Prada Linea Rossa Sunglasses', 'price': 38500, 'img': 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=600&auto=format&fit=crop', 'desc': 'Prada Linea Rossa sunglasses in lightweight nylon. Features sporty design, red stripe, and Italian performance luxury. Active elegance.'},
    {'cat': 'Lifestyle', 'sub': 'Eyewear', 'brand': 'Dior', 'name': 'Dior So Real Sunglasses', 'price': 55000, 'img': 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&auto=format&fit=crop', 'desc': 'Dior So Real sunglasses in metal with mirrored lenses. Features architectural frame, CD logo, and French fashion house elegance. Avant-garde luxury eyewear.'},
    
    # Leather Goods (New Category)
    {'cat': 'Lifestyle', 'sub': 'Leather Goods', 'brand': 'Hermes', 'name': 'Hermes Birkin 25 Togo Black', 'price': 650000, 'img': 'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=600&auto=format&fit=crop', 'desc': 'Hermes Birkin 25 in Togo black leather with gold hardware. Features compact size, palladium hardware, and the iconic saddle stitch. The ultimate investment bag in miniature.'},
    {'cat': 'Lifestyle', 'sub': 'Leather Goods', 'brand': 'Louis Vuitton', 'name': 'Louis Vuitton Keepall 55 Bandouliere', 'price': 195000, 'img': 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&auto=format&fit=crop', 'desc': 'Louis Vuitton Keepall 55 travel bag in Monogram canvas. Features shoulder strap, leather trim, and spacious interior. The classic travel companion since 1930.'},
    {'cat': 'Lifestyle', 'sub': 'Leather Goods', 'brand': 'Goyard', 'name': 'Goyard Saint Louis Tote GM', 'price': 225000, 'img': 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=600&auto=format&fit=crop', 'desc': 'Goyard Saint Louis tote in Goyardine canvas. Features reversible design, detachable pouch, and hand-painted chevron pattern. The discreet luxury choice.'},
    {'cat': 'Lifestyle', 'sub': 'Leather Goods', 'brand': 'Moynat', 'name': 'Moynat Rejane Python', 'price': 385000, 'img': 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600&auto=format&fit=crop', 'desc': 'Moynat Rejane bag in python leather with M lock. Features structured silhouette, hand-painted edges, and French heritage craftsmanship. Rare and exclusive.'},
    {'cat': 'Lifestyle', 'sub': 'Leather Goods', 'brand': 'Delvaux', 'name': 'Delvaux Brillant PM', 'price': 425000, 'img': 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600&auto=format&fit=crop', 'desc': 'Delvaux Brillant PM in box calf with Leclasp. Features rigid frame, D-shaped front, and Belgian royal warrant. The oldest luxury leather goods house.'},
    {'cat': 'Lifestyle', 'sub': 'Leather Goods', 'brand': 'Loewe', 'name': 'Loewe Puzzle Bag Small', 'price': 285000, 'img': 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&auto=format&fit=crop', 'desc': 'Loewe Puzzle bag small in calf leather. Features geometric construction, anagram logo, and Jonathan Anderson\'s innovative design. Modern Spanish luxury.'},
    
    # Tableware (New Category)
    {'cat': 'Lifestyle', 'sub': 'Tableware', 'brand': 'Baccarat', 'name': 'Baccarat Harcourt Glasses Set', 'price': 125000, 'img': 'https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?w=600&auto=format&fit=crop', 'desc': 'Baccarat Harcourt set of 6 crystal glasses. Features diamond-cut stem, timeless design since 1841, and exceptional clarity. The glass of kings and queens.'},
    {'cat': 'Lifestyle', 'sub': 'Tableware', 'brand': 'Christofle', 'name': 'Christofle Silver Plated Cutlery Set', 'price': 285000, 'img': 'https://images.unsplash.com/photo-1533777857889-4be7c70b33f7?w=600&auto=format&fit=crop', 'desc': 'Christofle silver-plated cutlery set for 12. Features Malmaison pattern, French silver craftsmanship, and elegant presentation. Dining luxury since 1830.'},
    {'cat': 'Lifestyle', 'sub': 'Tableware', 'brand': 'Hermes', 'name': 'Hermes Hermes 3000 Dinnerware', 'price': 385000, 'img': 'https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?w=600&auto=format&fit=crop', 'desc': 'Hermes Hermes 3000 porcelain dinnerware set. Features horse-drawn carriage motif, gold rim, and Limoges porcelain. French elegance for the table.'},
    {'cat': 'Lifestyle', 'sub': 'Tableware', 'brand': 'Bernardaud', 'name': 'Bernardaud Louvre Dinner Plate', 'price': 8500, 'img': 'https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?w=600&auto=format&fit=crop', 'desc': 'Bernardaud Louvre dinner plate in Limoges porcelain. Features gold edge, classical motif, and French artisanal excellence. Museum-quality tableware.'},
    {'cat': 'Lifestyle', 'sub': 'Tableware', 'brand': 'Villeroy & Boch', 'name': 'Villeroy & Boch French Garden', 'price': 45000, 'img': 'https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?w=600&auto=format&fit=crop', 'desc': 'Villeroy & Boch French Garden dinnerware set. Features floral pattern, fine porcelain, and German craftsmanship. Romantic elegance for everyday dining.'},
    {'cat': 'Lifestyle', 'sub': 'Tableware', 'brand': 'Meissen', 'name': 'Meissen Blue Onion Tea Set', 'price': 485000, 'img': 'https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?w=600&auto=format&fit=crop', 'desc': 'Meissen Blue Onion tea set in hand-painted porcelain. Features iconic pattern, 300-year heritage, and German royal porcelain. The first European hard-paste porcelain.'}
]


def seed_database():
    with app.app_context():
        print("Clearing database...")
        CartItem.query.delete()
        Wishlist.query.delete()
        OrderItem.query.delete()
        Product.query.delete()
        Subcategory.query.delete()
        Category.query.delete()
        db.session.commit()
        
        # Build category map
        cats = {}
        subcats = {}
        
        print("Creating categories & products...")
        for p in PRODUCTS_DATA:
            if p['cat'] not in cats:
                category = Category(name=p['cat'])
                db.session.add(category)
                db.session.flush()
                cats[p['cat']] = category
                
            cat_obj = cats[p['cat']]
            sub_key = f"{p['cat']}-{p['sub']}"
            
            if sub_key not in subcats:
                sub = Subcategory(name=p['sub'], category_id=cat_obj.id)
                db.session.add(sub)
                db.session.flush()
                subcats[sub_key] = sub
                
            sub_obj = subcats[sub_key]
            
            product = Product(
                name=p['name'],
                description=p['desc'],
                price=p['price'],
                stock=random.choices([0, random.randint(1, 15)], weights=[10, 90])[0],
                brand=p['brand'],
                image_url=p['img'],
                category_id=cat_obj.id,
                subcategory_id=sub_obj.id,
                is_featured=random.choice([True, False, False])
            )
            db.session.add(product)
            
        db.session.commit()
        print(f"Successfully seeded {len(PRODUCTS_DATA)} perfectly matched luxury products without duplicates!")

if __name__ == '__main__':
    seed_database()
