"""add gender column

Revision ID: 38538b209ba9
Revises: cf7e2336c675
Create Date: 2026-06-07 13:10:42.199670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38538b209ba9'
down_revision = 'cf7e2336c675'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index('ix_orders_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_orders_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('gender')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('ix_orders_user_id')
        batch_op.drop_index('ix_orders_created_at')

    # ### end Alembic commands ###
