"""Add original_price to Product

Revision ID: cf7e2336c675
Revises: f4a2c8d9e1b0
Create Date: 2026-06-06 23:51:09.867461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf7e2336c675'
down_revision = 'f4a2c8d9e1b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('original_price')

    # ### end Alembic commands ###
